name: Keep Codespace Alive 24/7

on:
  schedule:
    - cron: '*/5 * * * *'  # This will run every 5 minutes

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
    - name: Keep Codespace Alive
      run: |
        curl -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
             -X POST "https://api.github.com/repos/${{ github.repository }}/codespaces/${{ secrets.CODESPACE_NAME }}/start"
